---
apiVersion: apps/v1
kind: deployment
metadata:
    name: k8s-deployment-blue-env
spec:
  replicas: 3
  strategy:
     type: RollingUpdate
  selector:
    matchLabels:
        app: k8s-demo-app
        version: v1
        color: blue

  template:
    metadata:
       labels:
          app: k8s-demo-app
          version: v1
          color: blue
    spec:
      containers:
      - name: nginxcontainer
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
...              
     
     