---
apiVersion: v1
kind: Pod
metadata:
   name: nginx
   labels:
      app: nginxwebapp
   namespace: pratibhans
spec:
  containers:
   - name: nginxcontainer
     image: nginx:latest
     ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
   name: nginxsvc
   namespace: pratibhans
spec:
  type: NodePort
  selector:
     app: nginxwebapp
  ports:
    - port: 90
      targetPort: 80
      nodePort: 30003
...
