---
apiVersion: v1
kind: Service
metadata:
  name: pythonsvc
spec:
  type: NodePort
  selector:
    app: k8s-python-app
    version: v2
  ports:
  - name: pythoncontainer
    protocol: TCP
    port: 90
    targetPort: 80
    nodePort: 300092
...  
