---
apiVersion: v1
kind: ReplicationController
metadata: 
   name: nginxwebapprc
spec:
  replicas: 1
  selector:
     app: nginxwebapp
  template:
    metadata:
       name: nginxpod
       labels:
         app: nginxwebapp
    spec:
      containers:
         - name: nginxcontainer
           image: nginx:latest
           ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
   name: nginxsvc
spec:
  type: NodePort
  selector: 
    app: nginxwebapp
  ports:
   - port: 90
     targetPort: 80
     nodePort: 30002
...                      
                         