---
apiVersion: v1
kind: Service
metadata: 
  name: nginxsvc
spec:
  type: NodePort
  selector:
    app:  k8s-demo-app
    version: v1
  ports:
    - name: nginxportmapping
      protocol: TCP
      port: 90
      targetPort: 80
      nodePort: 30005
...
        